#!/bin/sh
# Note: This script is executed from git root
export NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz

if [ $CI_PIPELINE_SOURCE != "schedule" ] && [ $CI_PIPELINE_SOURCE != "web" ]; then
    echo "Only scheduled or manual jobs will run, consider successful"
    echo "TODO: This should probably test something meaningful like instantiantion of all derivations"
    exit 0
fi

mkdir -p ~/.ssh
nix-shell -p openssh --run 'ssh-keyscan github.com >> ~/.ssh/known_hosts'

nix-shell -p git --run 'git config --global user.name "emacs-overlay"'
nix-shell -p git --run 'git config --global user.email "emacs-overlay@nix-community"'
nix-shell -p git --run 'git remote set-url --push origin git@github.com:nix-community/emacs-overlay.git'

./update
./.ci/push
