#!/bin/sh
# Note: This script is executed from git root
export NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz

if [ $CI_PIPELINE_SOURCE != "schedule" ] && [ $CI_PIPELINE_SOURCE != "web" ]; then
    echo "Only scheduled or manual jobs will run"
    exit 1
fi

nix-shell -p git --run 'git config --global user.name "emacs-overlay"'
nix-shell -p git --run 'git config --global user.email "emacs-overlay@nix-community"'

./update
./.ci/push
